### PR TITLE
added job.getManifestInfo

### PR DESCRIPTION
**Pull request by andrepadez**

### CODE REVIEW

**Comment by moser4035** [comment]
Hi, thank you for your contribution. Next time it would be great if you could do the pull request on the develop branch. This makes it easier for us to handle our releases. Thanks again!

**Comment by andrepadez** [comment]
sure, i will. thanks

**Comment by andrepadez** [comment]
Can you please publish this to NPM?
Thanks

**Comment by dweinber** [comment]
v0.4.0 has just been published.

**Comment by andrepadez** [comment]
thank you

**Pull request merged**
